name: macOS

on: [push]

env:
  # TeamTalk unit test environment variables
  VIDEODEVICEID: None
  VERBOSE: 0

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Toolchain Dependencies
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: |
        brew update
        make depend-mac

    - name: Init TeamTalk Library submodules
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: |
        git submodule update --init Library/TeamTalkLib/test/testdata

    - name: Install TeamTalk Library Dependencies
      run: brew install doxygen

    - name: Build TeamTalk Library and Apps
      working-directory: ${{runner.workspace}}/TeamTalk5
      shell: bash
      run: |
        source env.sh
        make CMAKE_EXTRA="-DWEBRTC=OFF -DCATCH_UNITTEST=ON -DCATCH_UNITTEST_PERF=OFF" CMAKE_GENERATOR="Unix Makefiles" -C Build mac

    - name: Start TeamTalk Standard Server
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: |
        cp Library/TeamTalkLib/test/tt5srv.xml_template Server/tt5srv.xml
        Server/tt5srv -d -c Server/tt5srv.xml

    - name: Start TeamTalk Pro Server (encrypted)
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: |
        cp -f Library/TeamTalkLib/test/tt5prosrv.xml_template Server/tt5prosrv.xml
        cp Library/TeamTalkLib/test/ttservercert.pem Server/
        cp Library/TeamTalkLib/test/ttserverkey.pem Server/
        Server/tt5prosrv -d -wd Server/

    - name: Catch unit-test
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/test
      run: catchtt.app/Contents/MacOS/catchtt --durations yes

    - name: Stop TeamTalk Pro Server
      run: killall tt5prosrv

    - name: Stop TeamTalk Standard Server
      run: killall tt5srv

    - name: Doxygen Documentation
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make dox
