name: macOS

on: [push, pull_request]

env:
  # TeamTalk unit test environment variables
  GITHUBSKIP: 1
  INPUTDEVICEID: 1978
  OUTPUTDEVICEID: 1978
  VERBOSE: 0
  VIDEODEVICEID: None

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.*'
        modules: 'qtmultimedia qtspeech'

    - name: Refresh Homebrew repo
      run: brew update

    - name: Update packages
      run: brew upgrade && brew autoremove && brew cleanup

    - name: Print env
      run: printenv | sort

    - name: Install TeamTalk Library Dependencies
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make depend-mac

    - name: Build TeamTalk Library and Apps
      working-directory: ${{runner.workspace}}/TeamTalk5
      shell: bash
      run: make CMAKE_EXTRA="-DFEATURE_WEBRTC=OFF -DFEATURE_PORTAUDIO=OFF -DBUILD_TEAMTALK_LIBRARY_UNITTEST_CATCH2=ON -DBUILD_TEAMTALK_LIBRARY_UNITTEST_CATCH2_PERF=OFF -DBUILD_TEAMTALK_CLIENT_QTTEAMTALK_PRODUCT=ON -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install" -C Build mac

    - name: Start TeamTalk Standard Server
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: |
        cp Library/TeamTalkLib/test/tt5srv.xml_template Server/tt5srv.xml
        Server/tt5srv -d -c Server/tt5srv.xml

    - name: Start TeamTalk Pro Server (encrypted)
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: |
        cp -f Library/TeamTalkLib/test/tt5prosrv.xml_template Server/tt5prosrv.xml
        cp Library/TeamTalkLib/test/ttservercert.pem Server/
        cp Library/TeamTalkLib/test/ttserverkey.pem Server/
        cp Library/TeamTalkLib/test/ca.cer Server/
        Server/tt5prosrv -d -wd Server/

    - name: Catch unit-test
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/test
      run: catchtt.app/Contents/MacOS/catchtt --durations yes

    - name: Stop TeamTalk Servers
      run: killall tt5srv tt5prosrv

    - name: Run CMake Install Target
      working-directory: ${{runner.workspace}}/TeamTalk5/Build/build-mac
      run: cmake --build . --target install

    - name: Upload TeamTalk Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: teamtalksdk-macos
        path: ${{runner.workspace}}/install
