name: Ubuntu 22

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Refresh Ubuntu-repo
      run: sudo apt update

    - name: Update packages
      working-directory: ${{runner.workspace}}/TeamTalk5
      # Ensure FFmpeg doesn't detect additional dependencies
      run: |
        sudo apt remove libmagickcore-dev libmagickwand-dev libbz2-dev liblzma-dev
        sudo apt autoremove
        sudo apt install valgrind
        sudo make -C Build depend-ubuntu22
        dpkg -l

    - name: Install TeamTalk Library Dependencies
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: sudo make -C Build depend-ubuntu22

    - name: Build TeamTalk Library and Apps
      working-directory: ${{runner.workspace}}/TeamTalk5
      shell: bash
      run: |
        source env.sh
        make CMAKE_EXTRA="-DFEATURE_WEBRTC=OFF -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install" -C Build ubuntu22
        echo TEAMTALK_INSTALLDIR=${{runner.workspace}}/install>> $GITHUB_ENV

    - name: Doxygen Documentation
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make dox

    - name: Run CMake Install Target
      working-directory: ${{runner.workspace}}/TeamTalk5/Build/build-ubuntu22
      run: cmake --build . --target install

    - name: Upload TeamTalk Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: teamtalksdk-ubuntu22
        path: ${{runner.workspace}}/install
        
    - name: Make Ubuntu Archive
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: |
        source env.sh
        cd Setup/Portable
        make ubuntu22

    - name: Upload TeamTalk Portable artifact
      uses: actions/upload-artifact@v2
      with:
        name: teamtalk-ubuntu22
        path: ${{runner.workspace}}/TeamTalk5/Setup/Portable/teamtalk-*
